Document: jubatus
Title: Debian jubatus Manual
Author: <insert document author here>
Abstract: This manual describes what jubatus is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/jubatus/jubatus.sgml.gz

Format: postscript
Files: /usr/share/doc/jubatus/jubatus.ps.gz

Format: text
Files: /usr/share/doc/jubatus/jubatus.text.gz

Format: HTML
Index: /usr/share/doc/jubatus/html/index.html
Files: /usr/share/doc/jubatus/html/*.html
